import { test, expect } from '@playwright/test'

const password = 'Browser!Secure2026'
const api = 'http://localhost:8092/api'
async function login(page, telephone = '770990001', secret = password) {
  await page.goto('/login')
  await page.getByLabel('Numéro de téléphone').fill(telephone)
  await page.getByLabel('Mot de passe', { exact: true }).fill(secret)
  await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
  await expect(page).toHaveURL(/tableau-de-bord/)
}

test('une visite sans session revient à la connexion', async ({ page }) => {
  await page.goto('/tableau-de-bord')
  await expect(page).toHaveURL(/login/)
})

test('la direction consulte, recherche et crée les dossiers via la vraie API', async ({ page }, testInfo) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await login(page)
  await expect(page.getByRole('table')).toBeVisible()
  await expect(page.getByText('12 élève(s) · Page 1 / 2')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('dashboard-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: 'Suivant', exact: true }).click()
  await expect(page.getByText('12 élève(s) · Page 2 / 2')).toBeVisible()
  await page.getByLabel('Rechercher un élève par nom ou matricule').fill('Awa')
  await page.getByRole('button', { name: 'Rechercher', exact: true }).click()
  await expect(page.getByText('1 élève(s) · Page 1 / 1')).toBeVisible()
  await expect(page.getByRole('table').getByText('Awa Sarr')).toBeVisible()
  await page.getByLabel('Effacer la recherche').click()
  await expect(page.getByText('12 élève(s) · Page 1 / 2')).toBeVisible()

  await page.getByRole('navigation').getByRole('button', { name: 'Comptes & accès' }).click()
  await expect(page.getByRole('table')).toBeVisible()
  await page.getByRole('button', { name: 'Créer un compte', exact: true }).click()
  let dialog = page.getByRole('dialog')
  await dialog.getByLabel('Prénom', { exact: false }).fill('Seynabou')
  await dialog.getByLabel(/^Nom/).fill('TestBrowser')
  await dialog.getByLabel('Téléphone', { exact: false }).fill('770990010')
  const accountResponse = page.waitForResponse(r => r.url().endsWith('/v1/admin/users') && r.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  expect((await accountResponse).status()).toBe(201)
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('status').filter({ hasText: 'Compte créé' })).toBeVisible()
  await expect(page.getByRole('table').getByText('Seynabou TestBrowser')).toBeVisible()
  await page.getByRole('button', { name: 'Créer un compte', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Prénom', { exact: false }).fill('Doublon')
  await dialog.getByLabel(/^Nom/).fill('TestBrowser')
  await dialog.getByLabel('Téléphone', { exact: false }).fill('770990010')
  const invalidResponse = page.waitForResponse(r => r.url().endsWith('/v1/admin/users') && r.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  expect((await invalidResponse).status()).toBe(422)
  await expect(dialog.getByRole('alert')).toBeVisible()
  await dialog.getByRole('button', { name: 'Annuler' }).click()

  await page.getByRole('navigation').getByRole('button', { name: 'Élèves & inscriptions' }).click()
  await expect(page.getByRole('table')).toBeVisible()
  await page.getByRole('button', { name: 'Inscrire un élève', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Prénom', { exact: false }).first().fill('Nouveau')
  await dialog.getByLabel(/^Nom/).first().fill('TestBrowser')
  await dialog.getByLabel('Année scolaire', { exact: false }).fill('2026-2027')
  await dialog.getByLabel('Compte du tuteur').selectOption('existant')
  await dialog.getByLabel('Tuteur actif', { exact: false }).selectOption({ label: 'Aminata Fall · +221770990003' })
  const enrollment = page.waitForResponse(r => r.url().endsWith('/v1/eleves') && r.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  expect((await enrollment).status()).toBe(201)
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('table').getByText('Nouveau TestBrowser')).toBeVisible()
  await expect(page.getByRole('status').filter({ hasText: 'Matricule : ELV-' })).toBeVisible()

  await page.getByRole('button', { name: 'Inscrire un élève', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Prénom', { exact: false }).first().fill('LienMultiple')
  await dialog.getByLabel(/^Nom/).first().fill('TestBrowser')
  await dialog.getByLabel('Année scolaire', { exact: false }).fill('2026-2027')
  const guardianOne = dialog.getByRole('group', { name: 'Tuteur 1', exact: true })
  await guardianOne.getByLabel('Prénom', { exact: false }).fill('Moussa')
  await guardianOne.getByLabel(/^Nom/).fill('TestTuteur')
  await guardianOne.getByLabel('Téléphone', { exact: false }).fill('770990011')
  await guardianOne.getByLabel('Adresse', { exact: true }).fill('Dakar')
  await dialog.getByRole('button', { name: 'Ajouter un tuteur' }).click()
  const guardianTwo = dialog.getByRole('group', { name: 'Tuteur 2', exact: true })
  await guardianTwo.getByLabel('Compte du tuteur').selectOption('existant')
  await guardianTwo.getByLabel('Tuteur actif', { exact: false }).selectOption({ label: 'Seynabou TestBrowser · +221770990010' })
  const multipleGuardians = page.waitForResponse(r => r.url().endsWith('/v1/eleves') && r.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  const multipleResponse = await multipleGuardians
  expect(multipleResponse.status()).toBe(201)
  const multipleBody = await multipleResponse.json()
  expect(multipleBody.data.tuteurs).toHaveLength(2)
  expect(multipleBody.data.tuteurs[0].compte_cree).toBe(true)
  expect(multipleBody.data.eleve.a_un_compte).toBe(false)
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('table').getByText('LienMultiple TestBrowser')).toBeVisible()

  await page.getByRole('navigation').getByRole('button', { name: 'Classes académiques' }).click()
  await expect(page.getByRole('table')).toBeVisible()
  await page.getByRole('button', { name: 'Créer une classe', exact: true }).click()
  dialog = page.getByRole('dialog')
  await dialog.getByLabel('Nom de la classe', { exact: false }).fill('Classe TestBrowser')
  await dialog.getByLabel('Niveau', { exact: false }).fill('Intermédiaire')
  await dialog.getByLabel('Année scolaire', { exact: false }).fill('2026-2027')
  await dialog.getByLabel('Oustaz responsable', { exact: false }).selectOption({ label: 'Ibrahima Diop' })
  await dialog.getByRole('checkbox', { name: /Nouveau TestBrowser/ }).check()
  const creation = page.waitForResponse(r => r.url().endsWith('/v1/classes') && r.request().method() === 'POST')
  await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click()
  expect((await creation).status()).toBe(201)
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('table').getByText('Classe TestBrowser')).toBeVisible()
  await expect(page.getByRole('table').getByRole('row').filter({ hasText: 'Classe TestBrowser' })).toContainText('1 élèves')
  await page.getByRole('combobox', { name: 'Année scolaire', exact: true }).selectOption('2026-2027')
  await expect(page.getByText('4 classe(s) · Page 1 / 1')).toBeVisible()
  await page.getByLabel('Se déconnecter').click()
  await expect(page).toHaveURL(/login/)
  expect(errors).toEqual([])
})

test('un tuteur ne voit que ses élèves et ne peut pas lire le tableau direction', async ({ page, request }) => {
  await login(page, '770990003')
  await expect(page.getByRole('heading', { name: 'Mes élèves', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Awa Sarr', exact: true })).toBeVisible()
  await expect(page.getByRole('navigation').getByText('Comptes & accès')).toHaveCount(0)
  const token = await page.evaluate(() => localStorage.getItem('alhadi.auth.token'))
  const response = await request.get(`${api}/v1/admin/dashboard`, { headers: { Accept: 'application/json', Authorization: `Bearer ${token}` } })
  expect(response.status()).toBe(403)
})

test('un oustaz retrouve ses classes et les élèves affectés', async ({ page }) => {
  await login(page, '770990002')
  await expect(page.getByRole('heading', { name: 'Mes classes', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Halaqa Al-Falah', exact: true })).toBeVisible()
  await expect(page.getByText('Awa Sarr', { exact: false })).toBeVisible()
})

test('le premier accès impose le changement du mot de passe et une reconnexion', async ({ page }) => {
  await login(page, '770990004', 'passer')
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('heading', { name: 'Sécurisez votre compte' })).toBeVisible()
  await dialog.getByLabel('Nouveau mot de passe', { exact: false }).fill('abcdefghijklmnop')
  await dialog.getByLabel('Confirmer le mot de passe', { exact: false }).fill('abcdefghijklmnop')
  await dialog.getByRole('button', { name: 'Changer le mot de passe' }).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await dialog.getByLabel('Nouveau mot de passe', { exact: false }).fill('Changed!Secure2026')
  await dialog.getByLabel('Confirmer le mot de passe', { exact: false }).fill('Changed!Secure2026')
  await dialog.getByRole('button', { name: 'Changer le mot de passe' }).click()
  await expect(page).toHaveURL(/login/)
  await expect(page.getByRole('status')).toContainText('Mot de passe modifié')
  await login(page, '770990004', 'Changed!Secure2026')
  await expect(page.getByRole('heading', { name: 'Mes élèves', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('navigation et formulaire sont utilisables sur mobile sans débordement', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await login(page)
  await expect(page.getByRole('table')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('dashboard-mobile.png'), fullPage: true })
  await page.getByLabel('Ouvrir le menu').click()
  await page.getByRole('navigation').getByRole('button', { name: 'Classes académiques' }).click()
  await expect(page.getByRole('heading', { name: 'Classes académiques', exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Créer une classe', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('form-mobile.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('une panne réseau affiche une erreur et le bouton permet de réessayer', async ({ page }) => {
  await page.route('**/api/v1/admin/dashboard?*', route => route.abort())
  await login(page)
  await expect(page.getByRole('alert')).toContainText('Impossible de joindre le serveur')
  await page.unroute('**/api/v1/admin/dashboard?*')
  await page.getByRole('button', { name: 'Réessayer', exact: true }).click()
  await expect(page.getByRole('table')).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
})
